"""create_tables

Revision ID: 2e4540967efc
Revises: 9889e6b54145
Create Date: 2026-04-21 23:53:47.759093

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2e4540967efc"
down_revision: Union[str, Sequence[str], None] = "9889e6b54145"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "debats_temp",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("statut", sa.String(length=50), nullable=True),
        sa.Column("messages", sa.JSON(), nullable=True),
        sa.Column("proposition_juge", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "techniciens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nom", sa.String(length=100), nullable=True),
        sa.Column("prenom", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("competences", sa.JSON(), nullable=True),
        sa.Column("cv_texte", sa.String(), nullable=True),
        sa.Column("disponibilite", sa.Boolean(), nullable=True),
        sa.Column("charge_actuelle", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("titre", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("priorite", sa.String(length=10), nullable=True),
        sa.Column("environnement", sa.String(length=20), nullable=True),
        sa.Column("application", sa.String(length=100), nullable=True),
        sa.Column("statut", sa.String(length=50), nullable=True),
        sa.Column("score_difficulte", sa.Integer(), nullable=True),
        sa.Column("facteurs_score", sa.JSON(), nullable=True),
        sa.Column("analyse_nlp", sa.JSON(), nullable=True),
        sa.Column("technicien_assigne_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tickets")
    op.drop_table("techniciens")
    op.drop_table("debats_temp")
    # ### end Alembic commands ###
